version: 2.1

orbs:
    node: circleci/node@4.1.0

jobs:
    install-dependencies:
        executor:
            name: node/default
            tag: '14.16-browsers'
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      - v1-dependencies-
            - run:
                  name: Installing dependencies
                  command: npm install
            - save_cache:
                  key: v1-dependencies-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules

    # lint:
    #     executor:
    #         name: node/default
    #         tag: '14.16-browsers'
    #     steps:
    #         - checkout
    #         - node/install-packages
    #         - run:
    #               command: npm run lint

    test:
        resource_class: xlarge
        executor:
            name: node/default
            tag: '14.16-browsers'
        environment:
            CHROME_BIN: '/usr/bin/google-chrome'
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      - v1-dependencies-
            - run:
                  command: npm run test -- --no-watch --no-progress

    build:
        executor:
            name: node/default
            tag: '14.16-browsers'
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package-lock.json" }}
                      - v1-dependencies-
            - run:
                  command: |
                      npm run build:prod
            - persist_to_workspace:
                  root: .
                  paths:
                      - dist

workflows:
    build_and_test:
        jobs:
            - install-dependencies
            # - lint
            - test:
                  requires:
                      - install-dependencies
            - build:
                  requires:
                      - install-dependencies
